/**
 * Domain types for the `insights` table
 */
export type InsightRow = {
  id: number;
  brand: number;
  createdAt: string;
  text: string;
};

// `id` is omitted because it is auto-generated by the database.
export type InsightInsert = Omit<InsightRow, "id">;
// `createdAt` is omitted because coming from the server/controllers.
export type InsightCreateInput = Omit<InsightInsert, "createdAt">;
// `createdAt` is omitted because it should not be updated.
export type InsightUpdate = Partial<Omit<InsightRow, "id" | "createdAt">>;
